include:
  remote: "https://github.com/git-developer/docker-support/raw/feature/gitlab-ci/gitlab-ci/docker-template.yml"

variables:
  IMAGE_PLATFORMS: 'linux/amd64,linux/i386,linux/arm64,linux/arm/v7,linux/arm/v6'
  UPDATE_CHECK_URLS: 'https://github.com/git-developer/mqmgateway.git'
  UPDATE_CHECK_REF: 'feature/stdconv'
  BUILD_ARGS: 'REPO_URL=https://github.com/git-developer/mqmgateway REPO_BRANCH=feature/stdconv SKIP_TESTS=1'

read_application_tags:
  extends: .docker_support:.with_bare_image
  stage: post_build
  artifacts:
    paths:
    - tags
    - labels
  script:
  - set -euo pipefail
  - run() { docker run --rm "${IMAGE_NAME}:${BUILD_CACHE}" sh -c "${@}"; }

  - COMMIT_DATE="$(run '[ ! -r /opt/metadata/commit_date ] || cut -d " " -f 1 </opt/metadata/commit_date')"
  - COMMIT_SHORT_SHA="$(run '[ ! -r /opt/metadata/commit_short_sha ] || cat /opt/metadata/commit_short_sha')"
  - BUILD_ID="$(date -u +%Y%m%d_%H%M%S)-${IMAGE_REVISION:-${CI_COMMIT_SHORT_SHA}}-$(od -An -N5 -tu4 </dev/urandom | tr -d ' ' | head -c8)"

  - mkdir -p tags
  - echo >tags/build_id "${IMAGE_NAME}:b${BUILD_ID}"
  - |
    if [ "${COMMIT_DATE}" ]; then
      APP_VERSION="${COMMIT_DATE}.${COMMIT_SHORT_SHA}"
      echo >tags/commit_info "${IMAGE_NAME}:${APP_VERSION}"
      mkdir -p labels
      echo >labels/org.opencontainers.image.version "org.opencontainers.image.version=${APP_VERSION}"
    fi
