name: Multi-Platform Build and Publish

on:
  workflow_dispatch:
    inputs:
      registry:
        description: "Target registry"
        type: choice
        default: GitHub Container Registry
        options:
          - GitHub Container Registry
          - Docker Hub
      platforms:
        description: 'Target platforms in JSON list syntax'
        default: '[ "linux/amd64", "linux/arm/v7" ]'
      build-args:
        description: 'Build arguments for the image'

jobs:
  build-ghcr:
    if: inputs.registry == 'GitHub Container Registry'
    permissions:
      packages: write
    uses: ./.github/workflows/build-ghcr.yml
    with:
      platforms:      ${{ inputs.platforms }}
      build-args:     ${{ inputs.build-args }}

  build-dockerhub:
    if: inputs.registry == 'Docker Hub'
    uses: ./.github/workflows/build-dockerhub.yml
    with:
      platforms:      ${{ inputs.platforms }}
      build-args:     ${{ inputs.build-args }}
