name: to-env
description: 'Remove prefix from JSON properties and convert to env format'
inputs:
  prefix:
    description: 'Prefix of properties that should be processed'
  properties:
    description: 'String representation of a JSON object containing the properties to convert'
    required: true
outputs:
  result:
    description: "JSON array of env-formatted properties"
    value: ${{ steps.transform.outputs.result }}
runs:
  using: "composite"
  steps:
    - id: transform
      env:
        prefix: ${{ inputs.prefix }}
        properties: ${{ inputs.properties }}
      uses: actions/github-script@v6
      with:
        script: |
          const prefix = process.env.prefix;
          return Object.entries(JSON.parse(process.env.properties))
            .filter(([key, value]) => key.startsWith(prefix) && value)
            .map(([key, value]) => key.replace(prefix, '').concat('=', value));
