name: Multi-Platform Build and Publish to Docker Hub

on:
  workflow_call:
    inputs:
      platforms:
        description: 'Target platforms in JSON list syntax, e.g. [ "linux/amd64", "linux/arm/v7" ]'
        type: string
      build-args:
        description: 'Build arguments for the image in JSON list syntax, e.g. [ "ARG1=foo", "ARG2=bar" ]'
        type: string

jobs:
  build-multi-platform-for-dockerhub:
    uses: .github/workflows/build-multi-platform.yml
    with:
      registry:       docker.io
      username:       ${{ vars.DOCKERHUB_USERNAME }}
      registry-image: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
      platforms:      ${{ inputs.platforms }}
      build-args:     ${{ inputs.build-args }}
    secrets:
      password:       ${{ secrets.DOCKERHUB_TOKEN }}
