name: build-and-publish

on:
  workflow_call:
    inputs:
      registry:
        type: string
        default: ghcr.io
      platforms:
        default: '[ "linux/amd64", "linux/arm/v7" ]'
      build-args:

jobs:
  build-multiarch-ghcr:
    if: contains(fromJSON('["ghcr.io", "", null]'), inputs.registry)
    permissions:
      packages: write
    uses: ./.github/workflows/build-multiarch.yml
    with:
      registry:       ghcr.io
      username:       ${{ github.actor }}
      registry-image: ghcr.io/${{ github.repository }}
      platforms:      ${{ inputs.platforms }}
      build-args:     ${{ inputs.build-args }}
    secrets:
      password:       ${{ secrets.GITHUB_TOKEN }}

  build-multiarch-dockerhub:
    if: inputs.registry == 'docker.io'
    uses: ./.github/workflows/build-multiarch.yml
    with:
      registry:       docker.io
      username:       ${{ vars.DOCKERHUB_USERNAME }}
      registry-image: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
      platforms:      ${{ inputs.platforms }}
      build-args:     ${{ inputs.build-args }}
    secrets:
      password:       ${{ secrets.DOCKERHUB_TOKEN }}
