name: Debug

on:
  # note: workflow_dispatch requires this workflow file to be on the default branch
  workflow_dispatch:
    inputs:
      registry:
        description: 'Target registry'
        type: choice
        options:
          - GitHub Container Registry
          - Docker Hub
        default: GitHub Container Registry
      platforms:
        description: 'Target platforms in JSON list syntax'
        default: '[ "linux/amd64", "linux/arm/v6", "linux/arm/v7", "linux/arm64", "linux/i386" ]'
      buildarg-alpine-version:
        description: 'Version of Alpine Linux base image'
        default: latest
      buildarg-exprtk-url:
        description: 'URL to exprtk header file'
        default: 'https://github.com/ArashPartow/exprtk/raw/master/exprtk.hpp'
      buildarg-test-skip:
        description: 'Skip tests?'
        type: boolean
        default: false
      buildarg-test-allow-failure:
        description: 'Continue build if tests fail?'
        type: boolean
        default: false

jobs:
  inputs-to-array:
    runs-on: ubuntu-latest
    env:
      PREFIX: 'buildarg-'
      INPUTS: ${{ toJSON(inputs) }}
    outputs:
      result: ${{ steps.run-script.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: run-script
        with:
          script: |
            const prefix = process.env.PREFIX;
            return JSON.stringify(Object.entries(JSON.parse(process.env.INPUTS))
              .filter(([key, value]) => key.startsWith(prefix))
              .map(([key, value]) =>
                key.replace(prefix, '')
                   .toUpperCase()
                   .replaceAll(/[^\w]/g, '_')
                   .concat('=', value)));
  job2:
    runs-on: ubuntu-latest
    needs: inputs-to-array
    steps:
      - run: echo "${{needs.inputs-to-array.outputs.result}}"

  job3:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.to-env.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - id: to-env
        uses: ./.github/actions/to-env
        with:
          prefix: 'buildarg-'
          properties: ${{ toJSON(inputs) }}
  job4:
    runs-on: ubuntu-latest
    needs: job3
    env:
      ARGS: ${{ join(fromJSON(needs.job3.outputs.result), fromJSON('"\n"')) }}
    steps:
      - run: echo "$ARGS"
