name: Debug

on:
  # note: workflow_dispatch requires this workflow file to be on the default branch
  workflow_dispatch:
    inputs:
      registry:
        description: 'Target registry'
        type: choice
        options:
          - GitHub Container Registry
          - Docker Hub
        default: GitHub Container Registry
      platforms:
        description: 'Target platforms in JSON list syntax'
        default: '[ "linux/amd64", "linux/arm/v6", "linux/arm/v7", "linux/arm64", "linux/i386" ]'
      buildarg-alpine-version:
        description: 'Version of Alpine Linux base image'
        default: latest
      buildarg-exprtk-url:
        description: 'URL to exprtk header file'
        default: 'https://github.com/ArashPartow/exprtk/raw/master/exprtk.hpp'
      buildarg-test-skip:
        description: 'Skip tests?'
        type: boolean
        default: false
      buildarg-test-allow-failure:
        description: 'Continue build if tests fail?'
        type: boolean
        default: false
      buildarg-test-timeout:
        description: 'Timeout for tests (in ms)'
        type: number
        default: 400
      buildarg-test-loglevel:
        description: 'Log level for tests (1-5, higher is more verbose)'
        type: choice
        options: [ 1, 2, 3, 4, 5 ]
        default: 3

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      VALUE: ${{ inputs.buildarg-alpine-version }}
#      DATA: ${{ toJSON(inputs.*) }}
    outputs:
      job-result: ${{steps.step1.outputs.result}}
    steps:
      - uses: actions/github-script@v6
        id: step1
        with:
          result-encoding: string
          script: |
            const prefix = 'buildarg-';
            return JSON.stringify(Object.entries(process.env));
            JSON.stringify(Object.entries(process.env)
              .filter(([key, value]) => key.startsWith(prefix))
              .map(([key, value]) =>
                key.replace(prefix, '')
                   .toUpperCase()
                   .replaceAll(/[^\w]/g, '_')
                   .concat('=', value)));
      - run: echo "${{steps.step1.outputs.result}}"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "${{needs.job1.outputs.job-result}}"
