name: build-and-publish


on:
  workflow_dispatch:
    inputs:
      registry-provider:
        type: choice
        default: ghcr.io
        options:
          - ghcr.io
          - docker.io

env:
  PLATFORMS: '[ "linux/amd64", "linux/arm/v6", "linux/arm/v7", "linux/arm64", "linux/i386" ]'
  BUILD_ARGS: |
    MQM_TEST_DEFAULT_WAIT_MS=400

jobs:
  build-multiarch-ghcr:
    if: contains(fromJSON('["ghcr.io", "", null]'), inputs.registry-provider)
    permissions:
      packages: write
    uses: ./.github/workflows/build-multiarch.yml
    with:
      platforms: ${{ env.PLATFORMS }}
      build-args: ${{ env.BUILD_ARGS }}

  build-multiarch-dockerhub:
    if: inputs.registry-provider == 'docker.io'
    uses: ./.github/workflows/build-multiarch.yml
    with:
      registry: docker.io
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry-image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
      platforms: ${{ env.PLATFORMS }}
      build-args: ${{ env.BUILD_ARGS }}
    secrets:
      password: ${{ secrets.DOCKERHUB_TOKEN }}
