name: trigger-build-and-publish

on:
  workflow_dispatch:
    inputs:
      registry:
        type: choice
        default: ghcr.io
        options:
          - ghcr.io
          - docker.io
      platforms:
        default: '[ "linux/amd64", "linux/arm/v6", "linux/arm/v7", "linux/arm64", "linux/i386" ]'
      build-args:
        default: |
          MQM_TEST_DEFAULT_WAIT_MS=400

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-and-publish.yml
    with:
      registry:       ${{ inputs.registry }}
      platforms:      ${{ inputs.platforms }}
      build-args:     ${{ inputs.build-args }}
    secrets: inherit
