name: build-and-publish

on:
  workflow_dispatch:
    inputs:
      registry-provider:
        type: choice
        default: ghcr.io
        options:
          - ghcr.io
          - docker.io
      platforms:
        default: '[ "linux/amd64", "linux/arm/v6", "linux/arm/v7", "linux/arm64", "linux/i386" ]'
      build-args:
        default: |
          MQM_TEST_DEFAULT_WAIT_MS=400
    secrets: inherit

jobs:
  build-multiarch-ghcr:
    if: contains(fromJSON('["ghcr.io", "", null]'), inputs.registry-provider)
    permissions:
      packages: write
    uses: ./.github/workflows/build-multiarch.yml
    with:
      platforms: ${{ inputs.platforms }}
      build-args: ${{ inputs.build-args }}

  build-multiarch-dockerhub:
    if: inputs.registry-provider == 'docker.io'
    uses: ./.github/workflows/build-multiarch.yml
    with:
      registry: docker.io
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry-image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
      platforms: ${{ inputs.platforms }}
      build-args: ${{ inputs.build-args }}
    secrets:
      password: ${{ secrets.DOCKERHUB_TOKEN }}
