name: Trigger Build and Publish
run-name: Build and publish to ${{ inputs.registry }}

on:
  # note: workflow_dispatch requires this workflow file to be on the default branch
  workflow_dispatch:
    inputs:
      registry:
        description: 'Target registry'
        type: string
#        type: choice
#        options:
#          - GitHub Container Registry
#          - Docker Hub
#        default: GitHub Container Registry
      platforms:
        description: 'Target platforms in JSON list syntax'
        default: '[ "linux/amd64", "linux/arm/v6", "linux/arm/v7", "linux/arm64", "linux/i386" ]'
      BUILD_ARG_ALPINE_VERSION:
        description: 'Version of Alpine Linux base image'
      BUILD_ARG_EXPRTK_URL:
        description: 'URL to exprtk header file'
      BUILD_ARG_MQM_TEST_SKIP:
        description: 'Skip tests?'
        type: boolean
      BUILD_ARG_MQM_TEST_ALLOW_FAILURE:
        description: 'Continue build if tests fail?'
        type: boolean
      BUILD_ARG_MQM_TEST_DEFAULT_WAIT_MS:
        description: 'Timeout for tests (in ms)'
        type: number
        default: 400
      BUILD_ARG_MQM_TEST_LOGLEVEL:
        description: 'Log level for tests (1-5, higher is more verbose)'
        type: choice
        options: [ 1, 2, 3, 4, 5 ]
        default: 3

  workflow_call:
    inputs:
      registry:
        description: 'Target registry'
        type: string
#        default: GitHub Container Registry
      platforms:
        description: 'Target platforms in JSON list syntax'
        type: string
        default: '[ "linux/amd64", "linux/arm/v6", "linux/arm/v7", "linux/arm64", "linux/i386" ]'
      BUILD_ARG_ALPINE_VERSION:
        description: 'Version of Alpine Linux base image'
        type: string
      BUILD_ARG_EXPRTK_URL:
        description: 'URL to exprtk header file'
        type: string
      BUILD_ARG_MQM_TEST_SKIP:
        description: 'Skip tests?'
        type: boolean
      BUILD_ARG_MQM_TEST_ALLOW_FAILURE:
        description: 'Continue build if tests fail?'
        type: boolean
      BUILD_ARG_MQM_TEST_DEFAULT_WAIT_MS:
        description: 'Timeout for tests (in ms)'
        type: number
        default: 400
      BUILD_ARG_MQM_TEST_LOGLEVEL:
        description: 'Log level for tests (1-5, higher is more verbose)'
        type: number
        default: 3

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.to-env.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - id: to-env
        uses: ./.github/actions/to-env
        with:
          prefix: BUILD_ARG_
          properties: ${{ toJSON(inputs) }}

  build-multi-platform-to-ghcr:
    if: |
      inputs.registry == 'GitHub Container Registry'
      || (!inputs.registry && !(vars.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN))
    permissions:
      packages: write
    uses: ./.github/workflows/build-ghcr.yml
    needs: prepare
    with:
      platforms:      ${{ inputs.platforms }}
      build-args:     ${{ needs.prepare.outputs.result }}

  build-multi-platform-to-dockerhub:
    if: |
      inputs.registry == 'Docker Hub'
      || (!inputs.registry && vars.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN)
    uses: ./.github/workflows/build-dockerhub.yml
    needs: prepare
    with:
      platforms:      ${{ inputs.platforms }}
      build-args:     ${{ needs.prepare.outputs.result }}
